DROP TABLE IF EXISTS pets;

CREATE TABLE pets (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    age int,
    kind text
);

INSERT INTO pets(age, name, kind) VALUES (7, 'Fido', 'dog');
INSERT INTO pets(age, name, kind) VALUES (5, 'Buttons', 'snake');